# Generated by Django 3.2.17 on 2023-03-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ecestudents'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ecestudents',
            table='EceStudents',
        ),
    ]
