# Generated by Django 3.2.17 on 2023-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ecestudents_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecestudents',
            old_name='age',
            new_name='std_age',
        ),
        migrations.RenameField(
            model_name='ecestudents',
            old_name='email',
            new_name='std_email',
        ),
        migrations.RenameField(
            model_name='ecestudents',
            old_name='pass_word',
            new_name='std_pass_word',
        ),
    ]
