# Generated by Django 3.2.17 on 2023-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230321_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CseStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'CseStudents',
            },
        ),
    ]
